In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('Social_Network_Ads.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype='int')
dataset.drop('User ID',axis=1)

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [4]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [5]:
indep=dataset[['Gender_Male','Age','EstimatedSalary']]
dep=dataset[['Purchased']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
x_train=scx.fit_transform(x_train)
x_test=scx.transform(x_test)

In [7]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid={'kernel':['linear','rbf','sigmoid','poly'],'gamma':['auto','scale'],'C':[10,100,500,1000,1500]}
grid=GridSearchCV(SVC(probability=True),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 500, 1000, 1500],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'sigmoid', 'poly']},
             scoring='f1_weighted', verbose=3)

In [8]:
result=grid.cv_results_
grid_prediction=grid.predict(x_test)

In [9]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)
print('confusion matrix:\n',cm)

confusion matrix:
 [[73  6]
 [ 4 37]]


In [10]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_prediction)
print('The clf report :\n',clf_report)

The clf report :
               precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120



In [11]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average='weighted')
print('The f1_macro value for the best parameters {}:'.format(grid.best_params_),f1_macro)

The f1_macro value for the best parameters {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9171245421245421


In [12]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9654214263661625

In [13]:
table=pd.DataFrame.from_dict(result)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.023540      0.002242         0.014202        0.003741      10   
1        0.019622      0.002051         0.013932        0.002903      10   
2        0.015046      0.004336         0.012796        0.001524      10   
3        0.022584      0.002790         0.015752        0.004098      10   
4        0.019494      0.002718         0.010779        0.002516      10   
5        0.015301      0.003150         0.012509        0.002334      10   
6        0.012664      0.002002         0.011395        0.001801      10   
7        0.017051      0.003602         0.012621        0.003526      10   
8        0.053333      0.004677         0.011208        0.002097     100   
9        0.020318      0.002042         0.011478        0.002439     100   
10       0.016146      0.001752         0.013275        0.003975     100   
11       0.061918      0.017304         0.011888        0.000941     100   
12       0.060071      0.010261         0.008805        0.004066     100   
13       0.022831      0.004390         0.011554        0.003607     100   
14       0.015147      0.003422         0.010062        0.002306     100   
15       0.056960      0.013734         0.009962        0.001983     100   
16       0.150283      0.011847         0.010742        0.001717     500   
17       0.037941      0.005394         0.009710        0.003747     500   
18       0.016397      0.005140         0.012678        0.004018     500   
19       0.226028      0.045269         0.011570        0.003078     500   
20       0.162747      0.019507         0.007491        0.002325     500   
21       0.044621      0.009278         0.009207        0.000957     500   
22       0.014618      0.003895         0.009217        0.004184     500   
23       0.246818      0.071114         0.014583        0.003925     500   
24       0.373268      0.087795         0.009737        0.002164    1000   
25       0.065261      0.005410         0.009711        0.001690    1000   
26       0.011086      0.001806         0.011778        0.003796    1000   
27       0.348724      0.114175         0.009493        0.005572    1000   
28       0.338334      0.048878         0.006368        0.003793    1000   
29       0.061312      0.009317         0.008057        0.001932    1000   
30       0.009291      0.001614         0.010904        0.001598    1000   
31       0.416329      0.132337         0.009961        0.001719    1000   
32       0.458669      0.065545         0.007716        0.004090    1500   
33       0.083278      0.016023         0.009662        0.001092    1500   
34       0.012533      0.004720         0.009524        0.001767    1500   
35       0.561050      0.167193         0.008528        0.003117    1500   
36       0.469652      0.073845         0.009608        0.001273    1500   
37       0.078883      0.018398         0.009804        0.005611    1500   
38       0.014814      0.005338         0.010394        0.003502    1500   
39       0.510063      0.099856         0.008990        0.002006    1500   

   param_gamma param_kernel  \
0         auto       linear   
1         auto          rbf   
2         auto      sigmoid   
3         auto         poly   
4        scale       linear   
5        scale          rbf   
6        scale      sigmoid   
7        scale         poly   
8         auto       linear   
9         auto          rbf   
10        auto      sigmoid   
11        auto         poly   
12       scale       linear   
13       scale          rbf   
14       scale      sigmoid   
15       scale         poly   
16        auto       linear   
17        auto          rbf   
18        auto      sigmoid   
19        auto         poly   
20       scale       linear   
21       scale          rbf   
22       scale      sigmoid   
23       scale         poly   
24        auto       linear   
25        auto          rbf   
26        auto      sigmoid   
27        auto     

In [14]:
import pickle

In [15]:
filename='Final_model_on_SVC.sav'
filename1='scx.pkl'
pickle.dump(grid,open(filename,'wb'))
pickle.dump(scx,open(filename1,'wb'))

In [16]:
preinput=scx.transform([[0,30,80000]])
preinput

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.00716855, -0.77101313,  0.29476771]])

In [17]:
loaded_model=pickle.load(open('Final_model_on_SVC.sav','rb'))
scx=pickle.load(open('scx.pkl','rb'))
result=loaded_model.predict(preinput)
result

array([0], dtype=int64)